import Link from "next/link";
import { ArrowRight, HeartHandshake, Trophy, Users } from "lucide-react";
import { SiteFooter, SiteHeader } from "../_components/site-chrome";
import styles from "../engagement.module.css";

export default function FundraisePage(){return <main className={styles.shell}><SiteHeader/>
<section className={styles.hero}><div className={styles.heroInner}><div className={styles.eyebrow}>REFI · Fundraise</div><h1>Turn your challenge into a campaign.</h1><p>Play alone, challenge friends or rally a team. Fundraising turns a personal action into shared support for REFI Foundation.</p><div className={styles.actions}><Link className={styles.primary} href="/play">Start with a game <ArrowRight size={16}/></Link><Link className={styles.secondary} href="/donate">Make a donation <HeartHandshake size={16}/></Link></div></div></section>
<section className={styles.body}><div className={styles.container}><div className={styles.grid3}>
<article className={styles.card}><Users size={26}/><h2>Challenge friends</h2><p>Share your score and invite people to beat it. The challenge becomes the invitation.</p><Link className={styles.cardAction} href="/play">Play first <ArrowRight size={16}/></Link></article>
<article className={styles.card}><Trophy size={26}/><h2>Set a target</h2><p>Create a campaign around a personal, team or community fundraising goal once campaign creation is enabled.</p><span className={styles.cardAction}>Campaign setup coming next</span></article>
<article className={styles.card}><HeartHandshake size={26}/><h2>Show the impact</h2><p>Donors should understand what their support contributes to, with evidence rather than invented promises.</p><Link className={styles.cardAction} href="/impact">See our approach <ArrowRight size={16}/></Link></article>
</div><div style={{marginTop:70}} className={styles.grid2}><div><div className={styles.eyebrow} style={{color:"var(--refi-blue-700)"}}>How it will work</div><h2 style={{fontFamily:"'Playfair Display',Georgia,serif",fontSize:"clamp(38px,5vw,58px)",lineHeight:1.03}}>One journey, four steps.</h2></div><div><ol style={{margin:0,paddingLeft:24,fontSize:18,lineHeight:1.8}}><li>Play a Refi challenge.</li><li>Share your score or create a campaign.</li><li>Invite friends, teams or supporters.</li><li>Track donations and campaign progress.</li></ol><div className={styles.note} style={{marginTop:24}}>The campaign dashboard and individual fundraiser pages are the next implementation layer. No fabricated fundraising totals are displayed before real payment data exists.</div></div></div></div></section><SiteFooter/></main>}